name: Template Workflow

inputs:
  my_variable:
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
    - run: npm install
      
    - name: node index.js
      shell: bash
      run: echo teste
