name: Test Pipeline Template

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: |
        echo "Hello World!"
    - name: Test 2
      run: |
        echo "Hello World!"
    - name: Test 3
      run: |
        echo "Hello World!"
    - name: Test 4
      run: |
        echo "Hello World!"