name: Build Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: node20
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use local my-action
        uses: ./.github/actions/build
        with:
          app-name: 'Myapp'