name: Main Pipeline

on:
  push:
    branches: [devops]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - uses: ./.github/workflows
      - uses: ./.github/actions/build
        with:
          my_variable: "My name is Victor"
         