name: Build Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Check local directory
        run: |
          ls -ltrah 

      - name: Build
        uses: .github/actions/build/action.yml
        with:
          app-name: 'Myapp'