name: HelloWorld

on:
  workflow_dispatch:
  push:
    branches:
      - devops

jobs:
  build:
  steps:
    - name: Test
      uses: ./.github/workflows/infra-deploy.yml
      with:
        name: ${{ inputs.name }}
