name: HelloWorld

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        required: true
  push:
    branches:
      - devops

jobs:
  checkout:
    uses: ./.github/workflows/infra-deploy.yml
    with:
      name: ${{ inputs.name }}
