name: HelloWorld

inputs:
  name:
    description: 'Your name'
    required: true

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Your name'
        required: true
  push:
    branches:
      - devops

jobs:
  checkout:
    uses: ./.github/workflows/infra-deploy.yml
    with:
      name: ${{ inputs.name }}  
