name: HelloWorld

on:
  workflow_dispatch:
  push:
    branches:
      - devops

jobs:
  build:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/infra-deploy.yml
    with:
      name: "teste"
